# Generated by Django 4.1.3 on 2022-12-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name='IMAGE URL del proyecto')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
                ('repo_url', models.URLField(verbose_name='Repositorio GIT_URL')),
            ],
        ),
    ]
