# Generated by Django 4.1.3 on 2022-12-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0002_portafolio_created_at_portafolio_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
