# Generated by Django 4.1.3 on 2022-12-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0004_portafolio_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='portafolio',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
