# Generated by Django 4.1.3 on 2022-12-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0005_portafolio_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolio',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='image_url',
            field=models.URLField(verbose_name='Imagen del Proyecto (URL)'),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='repo_url',
            field=models.URLField(verbose_name='Repositorio Git (URL)'),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='tags',
            field=models.CharField(max_length=200, verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titulo del proyecto'),
        ),
    ]
